Document: libykneomgr
Title: Debian libykneomgr Manual
Author: <insert document author here>
Abstract: This manual describes what libykneomgr is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libykneomgr/libykneomgr.sgml.gz

Format: postscript
Files: /usr/share/doc/libykneomgr/libykneomgr.ps.gz

Format: text
Files: /usr/share/doc/libykneomgr/libykneomgr.text.gz

Format: HTML
Index: /usr/share/doc/libykneomgr/html/index.html
Files: /usr/share/doc/libykneomgr/html/*.html
